# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/apps/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /opt/apps/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /work/08474/ywwu/ls6/Galois

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /work/08474/ywwu/ls6/Galois

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/opt/apps/cmake/3.24.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/opt/apps/cmake/3.24.2/bin/cpack --config ./CPackSourceConfig.cmake /work/08474/ywwu/ls6/Galois/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/apps/cmake/3.24.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/apps/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/apps/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"apps\" \"dev\" \"lib\" \"tools\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/apps/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/apps/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/apps/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/apps/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/apps/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/apps/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /work/08474/ywwu/ls6/Galois/CMakeFiles /work/08474/ywwu/ls6/Galois//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /work/08474/ywwu/ls6/Galois/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/build
.PHONY : lib/fast

#=============================================================================
# Target rules for targets named apps

# Build rule for target.
apps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apps
.PHONY : apps

# fast build rule for target.
apps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apps.dir/build.make CMakeFiles/apps.dir/build
.PHONY : apps/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named galois_support

# Build rule for target.
galois_support: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 galois_support
.PHONY : galois_support

# fast build rule for target.
galois_support/fast:
	$(MAKE) $(MAKESILENT) -f libsupport/CMakeFiles/galois_support.dir/build.make libsupport/CMakeFiles/galois_support.dir/build
.PHONY : galois_support/fast

#=============================================================================
# Target rules for targets named unit-getenv

# Build rule for target.
unit-getenv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-getenv
.PHONY : unit-getenv

# fast build rule for target.
unit-getenv/fast:
	$(MAKE) $(MAKESILENT) -f libsupport/test/CMakeFiles/unit-getenv.dir/build.make libsupport/test/CMakeFiles/unit-getenv.dir/build
.PHONY : unit-getenv/fast

#=============================================================================
# Target rules for targets named unit-logging

# Build rule for target.
unit-logging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-logging
.PHONY : unit-logging

# fast build rule for target.
unit-logging/fast:
	$(MAKE) $(MAKESILENT) -f libsupport/test/CMakeFiles/unit-logging.dir/build.make libsupport/test/CMakeFiles/unit-logging.dir/build
.PHONY : unit-logging/fast

#=============================================================================
# Target rules for targets named galois_shmem

# Build rule for target.
galois_shmem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 galois_shmem
.PHONY : galois_shmem

# fast build rule for target.
galois_shmem/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/CMakeFiles/galois_shmem.dir/build.make libgalois/CMakeFiles/galois_shmem.dir/build
.PHONY : galois_shmem/fast

#=============================================================================
# Target rules for targets named unit-acquire

# Build rule for target.
unit-acquire: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-acquire
.PHONY : unit-acquire

# fast build rule for target.
unit-acquire/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-acquire.dir/build.make libgalois/test/CMakeFiles/unit-acquire.dir/build
.PHONY : unit-acquire/fast

#=============================================================================
# Target rules for targets named unit-bandwidth

# Build rule for target.
unit-bandwidth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-bandwidth
.PHONY : unit-bandwidth

# fast build rule for target.
unit-bandwidth/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-bandwidth.dir/build.make libgalois/test/CMakeFiles/unit-bandwidth.dir/build
.PHONY : unit-bandwidth/fast

#=============================================================================
# Target rules for targets named unit-barriers

# Build rule for target.
unit-barriers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-barriers
.PHONY : unit-barriers

# fast build rule for target.
unit-barriers/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-barriers.dir/build.make libgalois/test/CMakeFiles/unit-barriers.dir/build
.PHONY : unit-barriers/fast

#=============================================================================
# Target rules for targets named unit-empty-member-lcgraph

# Build rule for target.
unit-empty-member-lcgraph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-empty-member-lcgraph
.PHONY : unit-empty-member-lcgraph

# fast build rule for target.
unit-empty-member-lcgraph/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-empty-member-lcgraph.dir/build.make libgalois/test/CMakeFiles/unit-empty-member-lcgraph.dir/build
.PHONY : unit-empty-member-lcgraph/fast

#=============================================================================
# Target rules for targets named unit-flatmap

# Build rule for target.
unit-flatmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-flatmap
.PHONY : unit-flatmap

# fast build rule for target.
unit-flatmap/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-flatmap.dir/build.make libgalois/test/CMakeFiles/unit-flatmap.dir/build
.PHONY : unit-flatmap/fast

#=============================================================================
# Target rules for targets named unit-floatingPointErrors

# Build rule for target.
unit-floatingPointErrors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-floatingPointErrors
.PHONY : unit-floatingPointErrors

# fast build rule for target.
unit-floatingPointErrors/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-floatingPointErrors.dir/build.make libgalois/test/CMakeFiles/unit-floatingPointErrors.dir/build
.PHONY : unit-floatingPointErrors/fast

#=============================================================================
# Target rules for targets named unit-foreach

# Build rule for target.
unit-foreach: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-foreach
.PHONY : unit-foreach

# fast build rule for target.
unit-foreach/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-foreach.dir/build.make libgalois/test/CMakeFiles/unit-foreach.dir/build
.PHONY : unit-foreach/fast

#=============================================================================
# Target rules for targets named unit-forward-declare-graph

# Build rule for target.
unit-forward-declare-graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-forward-declare-graph
.PHONY : unit-forward-declare-graph

# fast build rule for target.
unit-forward-declare-graph/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-forward-declare-graph.dir/build.make libgalois/test/CMakeFiles/unit-forward-declare-graph.dir/build
.PHONY : unit-forward-declare-graph/fast

#=============================================================================
# Target rules for targets named unit-gcollections

# Build rule for target.
unit-gcollections: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-gcollections
.PHONY : unit-gcollections

# fast build rule for target.
unit-gcollections/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-gcollections.dir/build.make libgalois/test/CMakeFiles/unit-gcollections.dir/build
.PHONY : unit-gcollections/fast

#=============================================================================
# Target rules for targets named unit-graph

# Build rule for target.
unit-graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-graph
.PHONY : unit-graph

# fast build rule for target.
unit-graph/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-graph.dir/build.make libgalois/test/CMakeFiles/unit-graph.dir/build
.PHONY : unit-graph/fast

#=============================================================================
# Target rules for targets named unit-graph-compile

# Build rule for target.
unit-graph-compile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-graph-compile
.PHONY : unit-graph-compile

# fast build rule for target.
unit-graph-compile/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-graph-compile.dir/build.make libgalois/test/CMakeFiles/unit-graph-compile.dir/build
.PHONY : unit-graph-compile/fast

#=============================================================================
# Target rules for targets named unit-gslist

# Build rule for target.
unit-gslist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-gslist
.PHONY : unit-gslist

# fast build rule for target.
unit-gslist/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-gslist.dir/build.make libgalois/test/CMakeFiles/unit-gslist.dir/build
.PHONY : unit-gslist/fast

#=============================================================================
# Target rules for targets named unit-hwtopo

# Build rule for target.
unit-hwtopo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-hwtopo
.PHONY : unit-hwtopo

# fast build rule for target.
unit-hwtopo/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-hwtopo.dir/build.make libgalois/test/CMakeFiles/unit-hwtopo.dir/build
.PHONY : unit-hwtopo/fast

#=============================================================================
# Target rules for targets named unit-lc-adaptor

# Build rule for target.
unit-lc-adaptor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-lc-adaptor
.PHONY : unit-lc-adaptor

# fast build rule for target.
unit-lc-adaptor/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-lc-adaptor.dir/build.make libgalois/test/CMakeFiles/unit-lc-adaptor.dir/build
.PHONY : unit-lc-adaptor/fast

#=============================================================================
# Target rules for targets named unit-lock

# Build rule for target.
unit-lock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-lock
.PHONY : unit-lock

# fast build rule for target.
unit-lock/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-lock.dir/build.make libgalois/test/CMakeFiles/unit-lock.dir/build
.PHONY : unit-lock/fast

#=============================================================================
# Target rules for targets named unit-mem

# Build rule for target.
unit-mem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-mem
.PHONY : unit-mem

# fast build rule for target.
unit-mem/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-mem.dir/build.make libgalois/test/CMakeFiles/unit-mem.dir/build
.PHONY : unit-mem/fast

#=============================================================================
# Target rules for targets named unit-morphgraph

# Build rule for target.
unit-morphgraph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-morphgraph
.PHONY : unit-morphgraph

# fast build rule for target.
unit-morphgraph/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-morphgraph.dir/build.make libgalois/test/CMakeFiles/unit-morphgraph.dir/build
.PHONY : unit-morphgraph/fast

#=============================================================================
# Target rules for targets named unit-move

# Build rule for target.
unit-move: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-move
.PHONY : unit-move

# fast build rule for target.
unit-move/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-move.dir/build.make libgalois/test/CMakeFiles/unit-move.dir/build
.PHONY : unit-move/fast

#=============================================================================
# Target rules for targets named unit-oneach

# Build rule for target.
unit-oneach: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-oneach
.PHONY : unit-oneach

# fast build rule for target.
unit-oneach/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-oneach.dir/build.make libgalois/test/CMakeFiles/unit-oneach.dir/build
.PHONY : unit-oneach/fast

#=============================================================================
# Target rules for targets named unit-papi

# Build rule for target.
unit-papi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-papi
.PHONY : unit-papi

# fast build rule for target.
unit-papi/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-papi.dir/build.make libgalois/test/CMakeFiles/unit-papi.dir/build
.PHONY : unit-papi/fast

#=============================================================================
# Target rules for targets named unit-pc

# Build rule for target.
unit-pc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-pc
.PHONY : unit-pc

# fast build rule for target.
unit-pc/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-pc.dir/build.make libgalois/test/CMakeFiles/unit-pc.dir/build
.PHONY : unit-pc/fast

#=============================================================================
# Target rules for targets named unit-reduction

# Build rule for target.
unit-reduction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-reduction
.PHONY : unit-reduction

# fast build rule for target.
unit-reduction/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-reduction.dir/build.make libgalois/test/CMakeFiles/unit-reduction.dir/build
.PHONY : unit-reduction/fast

#=============================================================================
# Target rules for targets named unit-sort

# Build rule for target.
unit-sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-sort
.PHONY : unit-sort

# fast build rule for target.
unit-sort/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-sort.dir/build.make libgalois/test/CMakeFiles/unit-sort.dir/build
.PHONY : unit-sort/fast

#=============================================================================
# Target rules for targets named unit-static

# Build rule for target.
unit-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-static
.PHONY : unit-static

# fast build rule for target.
unit-static/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-static.dir/build.make libgalois/test/CMakeFiles/unit-static.dir/build
.PHONY : unit-static/fast

#=============================================================================
# Target rules for targets named unit-traits

# Build rule for target.
unit-traits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-traits
.PHONY : unit-traits

# fast build rule for target.
unit-traits/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-traits.dir/build.make libgalois/test/CMakeFiles/unit-traits.dir/build
.PHONY : unit-traits/fast

#=============================================================================
# Target rules for targets named unit-twoleveliteratora

# Build rule for target.
unit-twoleveliteratora: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-twoleveliteratora
.PHONY : unit-twoleveliteratora

# fast build rule for target.
unit-twoleveliteratora/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-twoleveliteratora.dir/build.make libgalois/test/CMakeFiles/unit-twoleveliteratora.dir/build
.PHONY : unit-twoleveliteratora/fast

#=============================================================================
# Target rules for targets named unit-wakeup-overhead

# Build rule for target.
unit-wakeup-overhead: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-wakeup-overhead
.PHONY : unit-wakeup-overhead

# fast build rule for target.
unit-wakeup-overhead/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-wakeup-overhead.dir/build.make libgalois/test/CMakeFiles/unit-wakeup-overhead.dir/build
.PHONY : unit-wakeup-overhead/fast

#=============================================================================
# Target rules for targets named unit-worklists-compile

# Build rule for target.
unit-worklists-compile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-worklists-compile
.PHONY : unit-worklists-compile

# fast build rule for target.
unit-worklists-compile/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-worklists-compile.dir/build.make libgalois/test/CMakeFiles/unit-worklists-compile.dir/build
.PHONY : unit-worklists-compile/fast

#=============================================================================
# Target rules for targets named unit-morphgraph-removal

# Build rule for target.
unit-morphgraph-removal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit-morphgraph-removal
.PHONY : unit-morphgraph-removal

# fast build rule for target.
unit-morphgraph-removal/fast:
	$(MAKE) $(MAKESILENT) -f libgalois/test/CMakeFiles/unit-morphgraph-removal.dir/build.make libgalois/test/CMakeFiles/unit-morphgraph-removal.dir/build
.PHONY : unit-morphgraph-removal/fast

#=============================================================================
# Target rules for targets named galois_dist_async

# Build rule for target.
galois_dist_async: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 galois_dist_async
.PHONY : galois_dist_async

# fast build rule for target.
galois_dist_async/fast:
	$(MAKE) $(MAKESILENT) -f libdist/CMakeFiles/galois_dist_async.dir/build.make libdist/CMakeFiles/galois_dist_async.dir/build
.PHONY : galois_dist_async/fast

#=============================================================================
# Target rules for targets named galois_gluon

# Build rule for target.
galois_gluon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 galois_gluon
.PHONY : galois_gluon

# fast build rule for target.
galois_gluon/fast:
	$(MAKE) $(MAKESILENT) -f libgluon/CMakeFiles/galois_gluon.dir/build.make libgluon/CMakeFiles/galois_gluon.dir/build
.PHONY : galois_gluon/fast

#=============================================================================
# Target rules for targets named pangolin

# Build rule for target.
pangolin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pangolin
.PHONY : pangolin

# fast build rule for target.
pangolin/fast:
	$(MAKE) $(MAKESILENT) -f libpangolin/CMakeFiles/pangolin.dir/build.make libpangolin/CMakeFiles/pangolin.dir/build
.PHONY : pangolin/fast

#=============================================================================
# Target rules for targets named distbench

# Build rule for target.
distbench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distbench
.PHONY : distbench

# fast build rule for target.
distbench/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/libdistbench/CMakeFiles/distbench.dir/build.make lonestar/libdistbench/CMakeFiles/distbench.dir/build
.PHONY : distbench/fast

#=============================================================================
# Target rules for targets named lonestar

# Build rule for target.
lonestar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lonestar
.PHONY : lonestar

# fast build rule for target.
lonestar/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/liblonestar/CMakeFiles/lonestar.dir/build.make lonestar/liblonestar/CMakeFiles/lonestar.dir/build
.PHONY : lonestar/fast

#=============================================================================
# Target rules for targets named example-sssp-push-simple

# Build rule for target.
example-sssp-push-simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-sssp-push-simple
.PHONY : example-sssp-push-simple

# fast build rule for target.
example-sssp-push-simple/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-sssp-push-simple.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-sssp-push-simple.dir/build
.PHONY : example-sssp-push-simple/fast

#=============================================================================
# Target rules for targets named example-sssp-simple

# Build rule for target.
example-sssp-simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-sssp-simple
.PHONY : example-sssp-simple

# fast build rule for target.
example-sssp-simple/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-sssp-simple.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-sssp-simple.dir/build
.PHONY : example-sssp-simple/fast

#=============================================================================
# Target rules for targets named example-sssp-pull-simple

# Build rule for target.
example-sssp-pull-simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-sssp-pull-simple
.PHONY : example-sssp-pull-simple

# fast build rule for target.
example-sssp-pull-simple/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-sssp-pull-simple.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-sssp-pull-simple.dir/build
.PHONY : example-sssp-pull-simple/fast

#=============================================================================
# Target rules for targets named example-hello-world

# Build rule for target.
example-hello-world: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-hello-world
.PHONY : example-hello-world

# fast build rule for target.
example-hello-world/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-hello-world.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-hello-world.dir/build
.PHONY : example-hello-world/fast

#=============================================================================
# Target rules for targets named example-torus

# Build rule for target.
example-torus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-torus
.PHONY : example-torus

# fast build rule for target.
example-torus/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-torus.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-torus.dir/build
.PHONY : example-torus/fast

#=============================================================================
# Target rules for targets named example-torus-improved

# Build rule for target.
example-torus-improved: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-torus-improved
.PHONY : example-torus-improved

# fast build rule for target.
example-torus-improved/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-torus-improved.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-torus-improved.dir/build
.PHONY : example-torus-improved/fast

#=============================================================================
# Target rules for targets named example-torus-construction

# Build rule for target.
example-torus-construction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-torus-construction
.PHONY : example-torus-construction

# fast build rule for target.
example-torus-construction/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-torus-construction.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-torus-construction.dir/build
.PHONY : example-torus-construction/fast

#=============================================================================
# Target rules for targets named example-graph-traversal-serial

# Build rule for target.
example-graph-traversal-serial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-graph-traversal-serial
.PHONY : example-graph-traversal-serial

# fast build rule for target.
example-graph-traversal-serial/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-graph-traversal-serial.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-graph-traversal-serial.dir/build
.PHONY : example-graph-traversal-serial/fast

#=============================================================================
# Target rules for targets named example-graph-traversal-pull

# Build rule for target.
example-graph-traversal-pull: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-graph-traversal-pull
.PHONY : example-graph-traversal-pull

# fast build rule for target.
example-graph-traversal-pull/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-graph-traversal-pull.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-graph-traversal-pull.dir/build
.PHONY : example-graph-traversal-pull/fast

#=============================================================================
# Target rules for targets named example-graph-traversal-push

# Build rule for target.
example-graph-traversal-push: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-graph-traversal-push
.PHONY : example-graph-traversal-push

# fast build rule for target.
example-graph-traversal-push/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-graph-traversal-push.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-graph-traversal-push.dir/build
.PHONY : example-graph-traversal-push/fast

#=============================================================================
# Target rules for targets named example-conflict-aware-torus

# Build rule for target.
example-conflict-aware-torus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-conflict-aware-torus
.PHONY : example-conflict-aware-torus

# fast build rule for target.
example-conflict-aware-torus/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-conflict-aware-torus.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-conflict-aware-torus.dir/build
.PHONY : example-conflict-aware-torus/fast

#=============================================================================
# Target rules for targets named example-spanningtree

# Build rule for target.
example-spanningtree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-spanningtree
.PHONY : example-spanningtree

# fast build rule for target.
example-spanningtree/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-spanningtree.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-spanningtree.dir/build
.PHONY : example-spanningtree/fast

#=============================================================================
# Target rules for targets named example-countlevels

# Build rule for target.
example-countlevels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-countlevels
.PHONY : example-countlevels

# fast build rule for target.
example-countlevels/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-countlevels.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-countlevels.dir/build
.PHONY : example-countlevels/fast

#=============================================================================
# Target rules for targets named example-malloc

# Build rule for target.
example-malloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-malloc
.PHONY : example-malloc

# fast build rule for target.
example-malloc/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-malloc.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-malloc.dir/build
.PHONY : example-malloc/fast

#=============================================================================
# Target rules for targets named example-wrapped-worklist

# Build rule for target.
example-wrapped-worklist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example-wrapped-worklist
.PHONY : example-wrapped-worklist

# fast build rule for target.
example-wrapped-worklist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/tutorial_examples/CMakeFiles/example-wrapped-worklist.dir/build.make lonestar/tutorial_examples/CMakeFiles/example-wrapped-worklist.dir/build
.PHONY : example-wrapped-worklist/fast

#=============================================================================
# Target rules for targets named betweennesscentrality-cpu

# Build rule for target.
betweennesscentrality-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 betweennesscentrality-cpu
.PHONY : betweennesscentrality-cpu

# fast build rule for target.
betweennesscentrality-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/betweennesscentrality/CMakeFiles/betweennesscentrality-cpu.dir/build.make lonestar/analytics/cpu/betweennesscentrality/CMakeFiles/betweennesscentrality-cpu.dir/build
.PHONY : betweennesscentrality-cpu/fast

#=============================================================================
# Target rules for targets named bfs-cpu

# Build rule for target.
bfs-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bfs-cpu
.PHONY : bfs-cpu

# fast build rule for target.
bfs-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/bfs/CMakeFiles/bfs-cpu.dir/build.make lonestar/analytics/cpu/bfs/CMakeFiles/bfs-cpu.dir/build
.PHONY : bfs-cpu/fast

#=============================================================================
# Target rules for targets named bfs-directionopt-cpu

# Build rule for target.
bfs-directionopt-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bfs-directionopt-cpu
.PHONY : bfs-directionopt-cpu

# fast build rule for target.
bfs-directionopt-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/bfs/CMakeFiles/bfs-directionopt-cpu.dir/build.make lonestar/analytics/cpu/bfs/CMakeFiles/bfs-directionopt-cpu.dir/build
.PHONY : bfs-directionopt-cpu/fast

#=============================================================================
# Target rules for targets named bipart-cpu

# Build rule for target.
bipart-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bipart-cpu
.PHONY : bipart-cpu

# fast build rule for target.
bipart-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/bipart/CMakeFiles/bipart-cpu.dir/build.make lonestar/analytics/cpu/bipart/CMakeFiles/bipart-cpu.dir/build
.PHONY : bipart-cpu/fast

#=============================================================================
# Target rules for targets named minimum-spanningtree-cpu

# Build rule for target.
minimum-spanningtree-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minimum-spanningtree-cpu
.PHONY : minimum-spanningtree-cpu

# fast build rule for target.
minimum-spanningtree-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/spanningtree/CMakeFiles/minimum-spanningtree-cpu.dir/build.make lonestar/analytics/cpu/spanningtree/CMakeFiles/minimum-spanningtree-cpu.dir/build
.PHONY : minimum-spanningtree-cpu/fast

#=============================================================================
# Target rules for targets named louvain-clustering-cpu

# Build rule for target.
louvain-clustering-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 louvain-clustering-cpu
.PHONY : louvain-clustering-cpu

# fast build rule for target.
louvain-clustering-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/clustering/CMakeFiles/louvain-clustering-cpu.dir/build.make lonestar/analytics/cpu/clustering/CMakeFiles/louvain-clustering-cpu.dir/build
.PHONY : louvain-clustering-cpu/fast

#=============================================================================
# Target rules for targets named leiden-clustering-cpu

# Build rule for target.
leiden-clustering-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leiden-clustering-cpu
.PHONY : leiden-clustering-cpu

# fast build rule for target.
leiden-clustering-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/clustering/CMakeFiles/leiden-clustering-cpu.dir/build.make lonestar/analytics/cpu/clustering/CMakeFiles/leiden-clustering-cpu.dir/build
.PHONY : leiden-clustering-cpu/fast

#=============================================================================
# Target rules for targets named connected-components-cpu

# Build rule for target.
connected-components-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 connected-components-cpu
.PHONY : connected-components-cpu

# fast build rule for target.
connected-components-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/connected-components/CMakeFiles/connected-components-cpu.dir/build.make lonestar/analytics/cpu/connected-components/CMakeFiles/connected-components-cpu.dir/build
.PHONY : connected-components-cpu/fast

#=============================================================================
# Target rules for targets named gmetis-cpu

# Build rule for target.
gmetis-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmetis-cpu
.PHONY : gmetis-cpu

# fast build rule for target.
gmetis-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/gmetis/CMakeFiles/gmetis-cpu.dir/build.make lonestar/analytics/cpu/gmetis/CMakeFiles/gmetis-cpu.dir/build
.PHONY : gmetis-cpu/fast

#=============================================================================
# Target rules for targets named maximal-independentset-cpu

# Build rule for target.
maximal-independentset-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 maximal-independentset-cpu
.PHONY : maximal-independentset-cpu

# fast build rule for target.
maximal-independentset-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/independentset/CMakeFiles/maximal-independentset-cpu.dir/build.make lonestar/analytics/cpu/independentset/CMakeFiles/maximal-independentset-cpu.dir/build
.PHONY : maximal-independentset-cpu/fast

#=============================================================================
# Target rules for targets named k-core-cpu

# Build rule for target.
k-core-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 k-core-cpu
.PHONY : k-core-cpu

# fast build rule for target.
k-core-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/k-core/CMakeFiles/k-core-cpu.dir/build.make lonestar/analytics/cpu/k-core/CMakeFiles/k-core-cpu.dir/build
.PHONY : k-core-cpu/fast

#=============================================================================
# Target rules for targets named k-truss-cpu

# Build rule for target.
k-truss-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 k-truss-cpu
.PHONY : k-truss-cpu

# fast build rule for target.
k-truss-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/k-truss/CMakeFiles/k-truss-cpu.dir/build.make lonestar/analytics/cpu/k-truss/CMakeFiles/k-truss-cpu.dir/build
.PHONY : k-truss-cpu/fast

#=============================================================================
# Target rules for targets named verify-k-truss

# Build rule for target.
verify-k-truss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 verify-k-truss
.PHONY : verify-k-truss

# fast build rule for target.
verify-k-truss/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/k-truss/CMakeFiles/verify-k-truss.dir/build.make lonestar/analytics/cpu/k-truss/CMakeFiles/verify-k-truss.dir/build
.PHONY : verify-k-truss/fast

#=============================================================================
# Target rules for targets named maximum-cardinality-matching-cpu

# Build rule for target.
maximum-cardinality-matching-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 maximum-cardinality-matching-cpu
.PHONY : maximum-cardinality-matching-cpu

# fast build rule for target.
maximum-cardinality-matching-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/matching/CMakeFiles/maximum-cardinality-matching-cpu.dir/build.make lonestar/analytics/cpu/matching/CMakeFiles/maximum-cardinality-matching-cpu.dir/build
.PHONY : maximum-cardinality-matching-cpu/fast

#=============================================================================
# Target rules for targets named matrixcompletion-cpu

# Build rule for target.
matrixcompletion-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrixcompletion-cpu
.PHONY : matrixcompletion-cpu

# fast build rule for target.
matrixcompletion-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/matrixcompletion/CMakeFiles/matrixcompletion-cpu.dir/build.make lonestar/analytics/cpu/matrixcompletion/CMakeFiles/matrixcompletion-cpu.dir/build
.PHONY : matrixcompletion-cpu/fast

#=============================================================================
# Target rules for targets named pagerank-pull-cpu

# Build rule for target.
pagerank-pull-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pagerank-pull-cpu
.PHONY : pagerank-pull-cpu

# fast build rule for target.
pagerank-pull-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/pagerank/CMakeFiles/pagerank-pull-cpu.dir/build.make lonestar/analytics/cpu/pagerank/CMakeFiles/pagerank-pull-cpu.dir/build
.PHONY : pagerank-pull-cpu/fast

#=============================================================================
# Target rules for targets named pagerank-push-cpu

# Build rule for target.
pagerank-push-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pagerank-push-cpu
.PHONY : pagerank-push-cpu

# fast build rule for target.
pagerank-push-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/pagerank/CMakeFiles/pagerank-push-cpu.dir/build.make lonestar/analytics/cpu/pagerank/CMakeFiles/pagerank-push-cpu.dir/build
.PHONY : pagerank-push-cpu/fast

#=============================================================================
# Target rules for targets named pointstoanalysis-cpu

# Build rule for target.
pointstoanalysis-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pointstoanalysis-cpu
.PHONY : pointstoanalysis-cpu

# fast build rule for target.
pointstoanalysis-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/pointstoanalysis/CMakeFiles/pointstoanalysis-cpu.dir/build.make lonestar/analytics/cpu/pointstoanalysis/CMakeFiles/pointstoanalysis-cpu.dir/build
.PHONY : pointstoanalysis-cpu/fast

#=============================================================================
# Target rules for targets named preflowpush-cpu

# Build rule for target.
preflowpush-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preflowpush-cpu
.PHONY : preflowpush-cpu

# fast build rule for target.
preflowpush-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/preflowpush/CMakeFiles/preflowpush-cpu.dir/build.make lonestar/analytics/cpu/preflowpush/CMakeFiles/preflowpush-cpu.dir/build
.PHONY : preflowpush-cpu/fast

#=============================================================================
# Target rules for targets named sssp-cpu

# Build rule for target.
sssp-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sssp-cpu
.PHONY : sssp-cpu

# fast build rule for target.
sssp-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/sssp/CMakeFiles/sssp-cpu.dir/build.make lonestar/analytics/cpu/sssp/CMakeFiles/sssp-cpu.dir/build
.PHONY : sssp-cpu/fast

#=============================================================================
# Target rules for targets named triangle-counting-cpu

# Build rule for target.
triangle-counting-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle-counting-cpu
.PHONY : triangle-counting-cpu

# fast build rule for target.
triangle-counting-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/cpu/triangle-counting/CMakeFiles/triangle-counting-cpu.dir/build.make lonestar/analytics/cpu/triangle-counting/CMakeFiles/triangle-counting-cpu.dir/build
.PHONY : triangle-counting-cpu/fast

#=============================================================================
# Target rules for targets named betweennesscentrality-level-dist

# Build rule for target.
betweennesscentrality-level-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 betweennesscentrality-level-dist
.PHONY : betweennesscentrality-level-dist

# fast build rule for target.
betweennesscentrality-level-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/betweennesscentrality/CMakeFiles/betweennesscentrality-level-dist.dir/build.make lonestar/analytics/distributed/betweennesscentrality/CMakeFiles/betweennesscentrality-level-dist.dir/build
.PHONY : betweennesscentrality-level-dist/fast

#=============================================================================
# Target rules for targets named betweennesscentrality-minrounds-dist

# Build rule for target.
betweennesscentrality-minrounds-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 betweennesscentrality-minrounds-dist
.PHONY : betweennesscentrality-minrounds-dist

# fast build rule for target.
betweennesscentrality-minrounds-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/betweennesscentrality/CMakeFiles/betweennesscentrality-minrounds-dist.dir/build.make lonestar/analytics/distributed/betweennesscentrality/CMakeFiles/betweennesscentrality-minrounds-dist.dir/build
.PHONY : betweennesscentrality-minrounds-dist/fast

#=============================================================================
# Target rules for targets named bfs-push-dist

# Build rule for target.
bfs-push-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bfs-push-dist
.PHONY : bfs-push-dist

# fast build rule for target.
bfs-push-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/bfs/CMakeFiles/bfs-push-dist.dir/build.make lonestar/analytics/distributed/bfs/CMakeFiles/bfs-push-dist.dir/build
.PHONY : bfs-push-dist/fast

#=============================================================================
# Target rules for targets named bfs-pull-dist

# Build rule for target.
bfs-pull-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bfs-pull-dist
.PHONY : bfs-pull-dist

# fast build rule for target.
bfs-pull-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/bfs/CMakeFiles/bfs-pull-dist.dir/build.make lonestar/analytics/distributed/bfs/CMakeFiles/bfs-pull-dist.dir/build
.PHONY : bfs-pull-dist/fast

#=============================================================================
# Target rules for targets named connected-components-push-dist

# Build rule for target.
connected-components-push-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 connected-components-push-dist
.PHONY : connected-components-push-dist

# fast build rule for target.
connected-components-push-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/connected-components/CMakeFiles/connected-components-push-dist.dir/build.make lonestar/analytics/distributed/connected-components/CMakeFiles/connected-components-push-dist.dir/build
.PHONY : connected-components-push-dist/fast

#=============================================================================
# Target rules for targets named connected-components-pull-dist

# Build rule for target.
connected-components-pull-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 connected-components-pull-dist
.PHONY : connected-components-pull-dist

# fast build rule for target.
connected-components-pull-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/connected-components/CMakeFiles/connected-components-pull-dist.dir/build.make lonestar/analytics/distributed/connected-components/CMakeFiles/connected-components-pull-dist.dir/build
.PHONY : connected-components-pull-dist/fast

#=============================================================================
# Target rules for targets named k-core-push-dist

# Build rule for target.
k-core-push-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 k-core-push-dist
.PHONY : k-core-push-dist

# fast build rule for target.
k-core-push-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/k-core/CMakeFiles/k-core-push-dist.dir/build.make lonestar/analytics/distributed/k-core/CMakeFiles/k-core-push-dist.dir/build
.PHONY : k-core-push-dist/fast

#=============================================================================
# Target rules for targets named k-core-pull-dist

# Build rule for target.
k-core-pull-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 k-core-pull-dist
.PHONY : k-core-pull-dist

# fast build rule for target.
k-core-pull-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/k-core/CMakeFiles/k-core-pull-dist.dir/build.make lonestar/analytics/distributed/k-core/CMakeFiles/k-core-pull-dist.dir/build
.PHONY : k-core-pull-dist/fast

#=============================================================================
# Target rules for targets named pagerank-pull-dist

# Build rule for target.
pagerank-pull-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pagerank-pull-dist
.PHONY : pagerank-pull-dist

# fast build rule for target.
pagerank-pull-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/pagerank/CMakeFiles/pagerank-pull-dist.dir/build.make lonestar/analytics/distributed/pagerank/CMakeFiles/pagerank-pull-dist.dir/build
.PHONY : pagerank-pull-dist/fast

#=============================================================================
# Target rules for targets named pagerank-push-dist

# Build rule for target.
pagerank-push-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pagerank-push-dist
.PHONY : pagerank-push-dist

# fast build rule for target.
pagerank-push-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/pagerank/CMakeFiles/pagerank-push-dist.dir/build.make lonestar/analytics/distributed/pagerank/CMakeFiles/pagerank-push-dist.dir/build
.PHONY : pagerank-push-dist/fast

#=============================================================================
# Target rules for targets named partition-dist

# Build rule for target.
partition-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 partition-dist
.PHONY : partition-dist

# fast build rule for target.
partition-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/partition/CMakeFiles/partition-dist.dir/build.make lonestar/analytics/distributed/partition/CMakeFiles/partition-dist.dir/build
.PHONY : partition-dist/fast

#=============================================================================
# Target rules for targets named matrixcompletion-dist

# Build rule for target.
matrixcompletion-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrixcompletion-dist
.PHONY : matrixcompletion-dist

# fast build rule for target.
matrixcompletion-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/matrixcompletion/CMakeFiles/matrixcompletion-dist.dir/build.make lonestar/analytics/distributed/matrixcompletion/CMakeFiles/matrixcompletion-dist.dir/build
.PHONY : matrixcompletion-dist/fast

#=============================================================================
# Target rules for targets named sssp-push-dist

# Build rule for target.
sssp-push-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sssp-push-dist
.PHONY : sssp-push-dist

# fast build rule for target.
sssp-push-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/sssp/CMakeFiles/sssp-push-dist.dir/build.make lonestar/analytics/distributed/sssp/CMakeFiles/sssp-push-dist.dir/build
.PHONY : sssp-push-dist/fast

#=============================================================================
# Target rules for targets named sssp-pull-dist

# Build rule for target.
sssp-pull-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sssp-pull-dist
.PHONY : sssp-pull-dist

# fast build rule for target.
sssp-pull-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/sssp/CMakeFiles/sssp-pull-dist.dir/build.make lonestar/analytics/distributed/sssp/CMakeFiles/sssp-pull-dist.dir/build
.PHONY : sssp-pull-dist/fast

#=============================================================================
# Target rules for targets named triangle-counting-dist

# Build rule for target.
triangle-counting-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle-counting-dist
.PHONY : triangle-counting-dist

# fast build rule for target.
triangle-counting-dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/analytics/distributed/triangle-counting/CMakeFiles/triangle-counting-dist.dir/build.make lonestar/analytics/distributed/triangle-counting/CMakeFiles/triangle-counting-dist.dir/build
.PHONY : triangle-counting-dist/fast

#=============================================================================
# Target rules for targets named aig-rewriting-cpu

# Build rule for target.
aig-rewriting-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aig-rewriting-cpu
.PHONY : aig-rewriting-cpu

# fast build rule for target.
aig-rewriting-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/eda/cpu/aig-rewriting/CMakeFiles/aig-rewriting-cpu.dir/build.make lonestar/eda/cpu/aig-rewriting/CMakeFiles/aig-rewriting-cpu.dir/build
.PHONY : aig-rewriting-cpu/fast

#=============================================================================
# Target rules for targets named sproute-cpu

# Build rule for target.
sproute-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sproute-cpu
.PHONY : sproute-cpu

# fast build rule for target.
sproute-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/eda/cpu/sproute/CMakeFiles/sproute-cpu.dir/build.make lonestar/eda/cpu/sproute/CMakeFiles/sproute-cpu.dir/build
.PHONY : sproute-cpu/fast

#=============================================================================
# Target rules for targets named miningbench

# Build rule for target.
miningbench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miningbench
.PHONY : miningbench

# fast build rule for target.
miningbench/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/mining/libminingbench/CMakeFiles/miningbench.dir/build.make lonestar/mining/libminingbench/CMakeFiles/miningbench.dir/build
.PHONY : miningbench/fast

#=============================================================================
# Target rules for targets named miningbench_dist

# Build rule for target.
miningbench_dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miningbench_dist
.PHONY : miningbench_dist

# fast build rule for target.
miningbench_dist/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/mining/libminingbench/CMakeFiles/miningbench_dist.dir/build.make lonestar/mining/libminingbench/CMakeFiles/miningbench_dist.dir/build
.PHONY : miningbench_dist/fast

#=============================================================================
# Target rules for targets named frequent-subgraph-mining-cpu

# Build rule for target.
frequent-subgraph-mining-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 frequent-subgraph-mining-cpu
.PHONY : frequent-subgraph-mining-cpu

# fast build rule for target.
frequent-subgraph-mining-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/mining/cpu/frequent-subgraph-mining/CMakeFiles/frequent-subgraph-mining-cpu.dir/build.make lonestar/mining/cpu/frequent-subgraph-mining/CMakeFiles/frequent-subgraph-mining-cpu.dir/build
.PHONY : frequent-subgraph-mining-cpu/fast

#=============================================================================
# Target rules for targets named k-clique-listing-cpu

# Build rule for target.
k-clique-listing-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 k-clique-listing-cpu
.PHONY : k-clique-listing-cpu

# fast build rule for target.
k-clique-listing-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/mining/cpu/k-clique-listing/CMakeFiles/k-clique-listing-cpu.dir/build.make lonestar/mining/cpu/k-clique-listing/CMakeFiles/k-clique-listing-cpu.dir/build
.PHONY : k-clique-listing-cpu/fast

#=============================================================================
# Target rules for targets named motif-counting-cpu

# Build rule for target.
motif-counting-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 motif-counting-cpu
.PHONY : motif-counting-cpu

# fast build rule for target.
motif-counting-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/mining/cpu/motif-counting/CMakeFiles/motif-counting-cpu.dir/build.make lonestar/mining/cpu/motif-counting/CMakeFiles/motif-counting-cpu.dir/build
.PHONY : motif-counting-cpu/fast

#=============================================================================
# Target rules for targets named triangle-counting-mining-cpu

# Build rule for target.
triangle-counting-mining-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle-counting-mining-cpu
.PHONY : triangle-counting-mining-cpu

# fast build rule for target.
triangle-counting-mining-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/mining/cpu/triangle-counting/CMakeFiles/triangle-counting-mining-cpu.dir/build.make lonestar/mining/cpu/triangle-counting/CMakeFiles/triangle-counting-mining-cpu.dir/build
.PHONY : triangle-counting-mining-cpu/fast

#=============================================================================
# Target rules for targets named barneshut-cpu

# Build rule for target.
barneshut-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 barneshut-cpu
.PHONY : barneshut-cpu

# fast build rule for target.
barneshut-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/scientific/cpu/barneshut/CMakeFiles/barneshut-cpu.dir/build.make lonestar/scientific/cpu/barneshut/CMakeFiles/barneshut-cpu.dir/build
.PHONY : barneshut-cpu/fast

#=============================================================================
# Target rules for targets named delaunayrefinement-cpu

# Build rule for target.
delaunayrefinement-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delaunayrefinement-cpu
.PHONY : delaunayrefinement-cpu

# fast build rule for target.
delaunayrefinement-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/scientific/cpu/delaunayrefinement/CMakeFiles/delaunayrefinement-cpu.dir/build.make lonestar/scientific/cpu/delaunayrefinement/CMakeFiles/delaunayrefinement-cpu.dir/build
.PHONY : delaunayrefinement-cpu/fast

#=============================================================================
# Target rules for targets named delaunaytriangulation-cpu

# Build rule for target.
delaunaytriangulation-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delaunaytriangulation-cpu
.PHONY : delaunaytriangulation-cpu

# fast build rule for target.
delaunaytriangulation-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/scientific/cpu/delaunaytriangulation/CMakeFiles/delaunaytriangulation-cpu.dir/build.make lonestar/scientific/cpu/delaunaytriangulation/CMakeFiles/delaunaytriangulation-cpu.dir/build
.PHONY : delaunaytriangulation-cpu/fast

#=============================================================================
# Target rules for targets named delaunaytriangulation-deterministic-cpu

# Build rule for target.
delaunaytriangulation-deterministic-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delaunaytriangulation-deterministic-cpu
.PHONY : delaunaytriangulation-deterministic-cpu

# fast build rule for target.
delaunaytriangulation-deterministic-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/scientific/cpu/delaunaytriangulation/CMakeFiles/delaunaytriangulation-deterministic-cpu.dir/build.make lonestar/scientific/cpu/delaunaytriangulation/CMakeFiles/delaunaytriangulation-deterministic-cpu.dir/build
.PHONY : delaunaytriangulation-deterministic-cpu/fast

#=============================================================================
# Target rules for targets named longestedge-cpu

# Build rule for target.
longestedge-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 longestedge-cpu
.PHONY : longestedge-cpu

# fast build rule for target.
longestedge-cpu/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/scientific/cpu/longestedge/CMakeFiles/longestedge-cpu.dir/build.make lonestar/scientific/cpu/longestedge/CMakeFiles/longestedge-cpu.dir/build
.PHONY : longestedge-cpu/fast

#=============================================================================
# Target rules for targets named longestedgeTest

# Build rule for target.
longestedgeTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 longestedgeTest
.PHONY : longestedgeTest

# fast build rule for target.
longestedgeTest/fast:
	$(MAKE) $(MAKESILENT) -f lonestar/scientific/cpu/longestedge/CMakeFiles/longestedgeTest.dir/build.make lonestar/scientific/cpu/longestedge/CMakeFiles/longestedgeTest.dir/build
.PHONY : longestedgeTest/fast

#=============================================================================
# Target rules for targets named input

# Build rule for target.
input: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 input
.PHONY : input

# fast build rule for target.
input/fast:
	$(MAKE) $(MAKESILENT) -f inputs/CMakeFiles/input.dir/build.make inputs/CMakeFiles/input.dir/build
.PHONY : input/fast

#=============================================================================
# Target rules for targets named graph-convert

# Build rule for target.
graph-convert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph-convert
.PHONY : graph-convert

# fast build rule for target.
graph-convert/fast:
	$(MAKE) $(MAKESILENT) -f tools/graph-convert/CMakeFiles/graph-convert.dir/build.make tools/graph-convert/CMakeFiles/graph-convert.dir/build
.PHONY : graph-convert/fast

#=============================================================================
# Target rules for targets named graph-convert-huge

# Build rule for target.
graph-convert-huge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph-convert-huge
.PHONY : graph-convert-huge

# fast build rule for target.
graph-convert-huge/fast:
	$(MAKE) $(MAKESILENT) -f tools/graph-convert/CMakeFiles/graph-convert-huge.dir/build.make tools/graph-convert/CMakeFiles/graph-convert-huge.dir/build
.PHONY : graph-convert-huge/fast

#=============================================================================
# Target rules for targets named graph-remap

# Build rule for target.
graph-remap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph-remap
.PHONY : graph-remap

# fast build rule for target.
graph-remap/fast:
	$(MAKE) $(MAKESILENT) -f tools/graph-remap/CMakeFiles/graph-remap.dir/build.make tools/graph-remap/CMakeFiles/graph-remap.dir/build
.PHONY : graph-remap/fast

#=============================================================================
# Target rules for targets named graph-stats

# Build rule for target.
graph-stats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph-stats
.PHONY : graph-stats

# fast build rule for target.
graph-stats/fast:
	$(MAKE) $(MAKESILENT) -f tools/graph-stats/CMakeFiles/graph-stats.dir/build.make tools/graph-stats/CMakeFiles/graph-stats.dir/build
.PHONY : graph-stats/fast

#=============================================================================
# Target rules for targets named dist-graph-convert

# Build rule for target.
dist-graph-convert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dist-graph-convert
.PHONY : dist-graph-convert

# fast build rule for target.
dist-graph-convert/fast:
	$(MAKE) $(MAKESILENT) -f tools/dist-graph-convert/CMakeFiles/dist-graph-convert.dir/build.make tools/dist-graph-convert/CMakeFiles/dist-graph-convert.dir/build
.PHONY : dist-graph-convert/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... apps"
	@echo "... doc"
	@echo "... input"
	@echo "... intrinsics_gen"
	@echo "... lib"
	@echo "... omp_gen"
	@echo "... aig-rewriting-cpu"
	@echo "... barneshut-cpu"
	@echo "... betweennesscentrality-cpu"
	@echo "... betweennesscentrality-level-dist"
	@echo "... betweennesscentrality-minrounds-dist"
	@echo "... bfs-cpu"
	@echo "... bfs-directionopt-cpu"
	@echo "... bfs-pull-dist"
	@echo "... bfs-push-dist"
	@echo "... bipart-cpu"
	@echo "... connected-components-cpu"
	@echo "... connected-components-pull-dist"
	@echo "... connected-components-push-dist"
	@echo "... delaunayrefinement-cpu"
	@echo "... delaunaytriangulation-cpu"
	@echo "... delaunaytriangulation-deterministic-cpu"
	@echo "... dist-graph-convert"
	@echo "... distbench"
	@echo "... example-conflict-aware-torus"
	@echo "... example-countlevels"
	@echo "... example-graph-traversal-pull"
	@echo "... example-graph-traversal-push"
	@echo "... example-graph-traversal-serial"
	@echo "... example-hello-world"
	@echo "... example-malloc"
	@echo "... example-spanningtree"
	@echo "... example-sssp-pull-simple"
	@echo "... example-sssp-push-simple"
	@echo "... example-sssp-simple"
	@echo "... example-torus"
	@echo "... example-torus-construction"
	@echo "... example-torus-improved"
	@echo "... example-wrapped-worklist"
	@echo "... frequent-subgraph-mining-cpu"
	@echo "... galois_dist_async"
	@echo "... galois_gluon"
	@echo "... galois_shmem"
	@echo "... galois_support"
	@echo "... gmetis-cpu"
	@echo "... graph-convert"
	@echo "... graph-convert-huge"
	@echo "... graph-remap"
	@echo "... graph-stats"
	@echo "... k-clique-listing-cpu"
	@echo "... k-core-cpu"
	@echo "... k-core-pull-dist"
	@echo "... k-core-push-dist"
	@echo "... k-truss-cpu"
	@echo "... leiden-clustering-cpu"
	@echo "... lonestar"
	@echo "... longestedge-cpu"
	@echo "... longestedgeTest"
	@echo "... louvain-clustering-cpu"
	@echo "... matrixcompletion-cpu"
	@echo "... matrixcompletion-dist"
	@echo "... maximal-independentset-cpu"
	@echo "... maximum-cardinality-matching-cpu"
	@echo "... minimum-spanningtree-cpu"
	@echo "... miningbench"
	@echo "... miningbench_dist"
	@echo "... motif-counting-cpu"
	@echo "... pagerank-pull-cpu"
	@echo "... pagerank-pull-dist"
	@echo "... pagerank-push-cpu"
	@echo "... pagerank-push-dist"
	@echo "... pangolin"
	@echo "... partition-dist"
	@echo "... pointstoanalysis-cpu"
	@echo "... preflowpush-cpu"
	@echo "... sproute-cpu"
	@echo "... sssp-cpu"
	@echo "... sssp-pull-dist"
	@echo "... sssp-push-dist"
	@echo "... triangle-counting-cpu"
	@echo "... triangle-counting-dist"
	@echo "... triangle-counting-mining-cpu"
	@echo "... unit-acquire"
	@echo "... unit-bandwidth"
	@echo "... unit-barriers"
	@echo "... unit-empty-member-lcgraph"
	@echo "... unit-flatmap"
	@echo "... unit-floatingPointErrors"
	@echo "... unit-foreach"
	@echo "... unit-forward-declare-graph"
	@echo "... unit-gcollections"
	@echo "... unit-getenv"
	@echo "... unit-graph"
	@echo "... unit-graph-compile"
	@echo "... unit-gslist"
	@echo "... unit-hwtopo"
	@echo "... unit-lc-adaptor"
	@echo "... unit-lock"
	@echo "... unit-logging"
	@echo "... unit-mem"
	@echo "... unit-morphgraph"
	@echo "... unit-morphgraph-removal"
	@echo "... unit-move"
	@echo "... unit-oneach"
	@echo "... unit-papi"
	@echo "... unit-pc"
	@echo "... unit-reduction"
	@echo "... unit-sort"
	@echo "... unit-static"
	@echo "... unit-traits"
	@echo "... unit-twoleveliteratora"
	@echo "... unit-wakeup-overhead"
	@echo "... unit-worklists-compile"
	@echo "... verify-k-truss"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

