# CMake generated Testfile for 
# Source directory: /work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart
# Build directory: /work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-small1-bipart-cpu-128 "/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/bipart-cpu" "-hMetisGraph" "/work/08474/ywwu/ls6/Galois/inputs/partitioning/ibm01.hgr" "-t" "128")
set_tests_properties(run-small1-bipart-cpu-128 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;5;add_test_scale;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;0;")
add_test(run-small1-bipart-cpu-64 "/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/bipart-cpu" "-hMetisGraph" "/work/08474/ywwu/ls6/Galois/inputs/partitioning/ibm01.hgr" "-t" "64")
set_tests_properties(run-small1-bipart-cpu-64 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;5;add_test_scale;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;0;")
add_test(run-small1-bipart-cpu-32 "/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/bipart-cpu" "-hMetisGraph" "/work/08474/ywwu/ls6/Galois/inputs/partitioning/ibm01.hgr" "-t" "32")
set_tests_properties(run-small1-bipart-cpu-32 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;5;add_test_scale;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;0;")
add_test(run-small1-bipart-cpu-16 "/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/bipart-cpu" "-hMetisGraph" "/work/08474/ywwu/ls6/Galois/inputs/partitioning/ibm01.hgr" "-t" "16")
set_tests_properties(run-small1-bipart-cpu-16 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;5;add_test_scale;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;0;")
add_test(run-small1-bipart-cpu-8 "/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/bipart-cpu" "-hMetisGraph" "/work/08474/ywwu/ls6/Galois/inputs/partitioning/ibm01.hgr" "-t" "8")
set_tests_properties(run-small1-bipart-cpu-8 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;5;add_test_scale;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;0;")
add_test(run-small1-bipart-cpu-4 "/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/bipart-cpu" "-hMetisGraph" "/work/08474/ywwu/ls6/Galois/inputs/partitioning/ibm01.hgr" "-t" "4")
set_tests_properties(run-small1-bipart-cpu-4 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;5;add_test_scale;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;0;")
add_test(run-small1-bipart-cpu-2 "/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/bipart-cpu" "-hMetisGraph" "/work/08474/ywwu/ls6/Galois/inputs/partitioning/ibm01.hgr" "-t" "2")
set_tests_properties(run-small1-bipart-cpu-2 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;5;add_test_scale;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;0;")
add_test(run-small1-bipart-cpu-1 "/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/bipart-cpu" "-hMetisGraph" "/work/08474/ywwu/ls6/Galois/inputs/partitioning/ibm01.hgr" "-t" "1")
set_tests_properties(run-small1-bipart-cpu-1 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;5;add_test_scale;/work/08474/ywwu/ls6/Galois/lonestar/analytics/cpu/bipart/CMakeLists.txt;0;")
