# CMake generated Testfile for 
# Source directory: /work/08474/ywwu/ls6/Galois/libgalois/test
# Build directory: /work/08474/ywwu/ls6/Galois/libgalois/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit-acquire "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-acquire")
set_tests_properties(unit-acquire PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;33;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-bandwidth "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-bandwidth")
set_tests_properties(unit-bandwidth PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;34;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-barriers "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-barriers" "1024" "2")
set_tests_properties(unit-barriers PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;35;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-empty-member-lcgraph "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-empty-member-lcgraph")
set_tests_properties(unit-empty-member-lcgraph PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;36;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-flatmap "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-flatmap")
set_tests_properties(unit-flatmap PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;37;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-floatingPointErrors "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-floatingPointErrors")
set_tests_properties(unit-floatingPointErrors PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;38;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-foreach "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-foreach")
set_tests_properties(unit-foreach PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;39;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-forward-declare-graph "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-forward-declare-graph")
set_tests_properties(unit-forward-declare-graph PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;40;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-gcollections "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-gcollections")
set_tests_properties(unit-gcollections PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;41;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-graph "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-graph")
set_tests_properties(unit-graph PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;42;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-graph-compile "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-graph-compile")
set_tests_properties(unit-graph-compile PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;43;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-gslist "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-gslist")
set_tests_properties(unit-gslist PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;44;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-hwtopo "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-hwtopo")
set_tests_properties(unit-hwtopo PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;45;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-lc-adaptor "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-lc-adaptor")
set_tests_properties(unit-lc-adaptor PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;46;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-lock "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-lock")
set_tests_properties(unit-lock PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;47;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-mem "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-mem")
set_tests_properties(unit-mem PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;49;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-morphgraph "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-morphgraph")
set_tests_properties(unit-morphgraph PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;50;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-move "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-move")
set_tests_properties(unit-move PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;51;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-oneach "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-oneach")
set_tests_properties(unit-oneach PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;52;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-papi "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-papi" "2")
set_tests_properties(unit-papi PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;53;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-pc "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-pc")
set_tests_properties(unit-pc PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;54;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-reduction "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-reduction")
set_tests_properties(unit-reduction PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;55;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-sort "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-sort")
set_tests_properties(unit-sort PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;56;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-static "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-static")
set_tests_properties(unit-static PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;57;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-traits "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-traits")
set_tests_properties(unit-traits PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;58;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-twoleveliteratora "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-twoleveliteratora")
set_tests_properties(unit-twoleveliteratora PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;59;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-wakeup-overhead "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-wakeup-overhead")
set_tests_properties(unit-wakeup-overhead PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;60;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-worklists-compile "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-worklists-compile")
set_tests_properties(unit-worklists-compile PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;61;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
add_test(unit-morphgraph-removal "/work/08474/ywwu/ls6/Galois/libgalois/test/unit-morphgraph-removal")
set_tests_properties(unit-morphgraph-removal PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;23;add_test;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;62;add_test_unit;/work/08474/ywwu/ls6/Galois/libgalois/test/CMakeLists.txt;0;")
