# CMake generated Testfile for 
# Source directory: /work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing
# Build directory: /work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-small1-k-clique-listing-cpu-128 "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/k-clique-listing-cpu" "-symmetricGraph" "-simpleGraph" "/work/08474/ywwu/ls6/Galois/inputs/Mining/citeseer.csgr" "-t" "128")
set_tests_properties(run-small1-k-clique-listing-cpu-128 PROPERTIES  _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;6;add_test_mine;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;0;")
add_test(run-small1-k-clique-listing-cpu-64 "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/k-clique-listing-cpu" "-symmetricGraph" "-simpleGraph" "/work/08474/ywwu/ls6/Galois/inputs/Mining/citeseer.csgr" "-t" "64")
set_tests_properties(run-small1-k-clique-listing-cpu-64 PROPERTIES  _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;6;add_test_mine;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;0;")
add_test(run-small1-k-clique-listing-cpu-32 "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/k-clique-listing-cpu" "-symmetricGraph" "-simpleGraph" "/work/08474/ywwu/ls6/Galois/inputs/Mining/citeseer.csgr" "-t" "32")
set_tests_properties(run-small1-k-clique-listing-cpu-32 PROPERTIES  _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;6;add_test_mine;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;0;")
add_test(run-small1-k-clique-listing-cpu-16 "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/k-clique-listing-cpu" "-symmetricGraph" "-simpleGraph" "/work/08474/ywwu/ls6/Galois/inputs/Mining/citeseer.csgr" "-t" "16")
set_tests_properties(run-small1-k-clique-listing-cpu-16 PROPERTIES  _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;6;add_test_mine;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;0;")
add_test(run-small1-k-clique-listing-cpu-8 "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/k-clique-listing-cpu" "-symmetricGraph" "-simpleGraph" "/work/08474/ywwu/ls6/Galois/inputs/Mining/citeseer.csgr" "-t" "8")
set_tests_properties(run-small1-k-clique-listing-cpu-8 PROPERTIES  _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;6;add_test_mine;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;0;")
add_test(run-small1-k-clique-listing-cpu-4 "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/k-clique-listing-cpu" "-symmetricGraph" "-simpleGraph" "/work/08474/ywwu/ls6/Galois/inputs/Mining/citeseer.csgr" "-t" "4")
set_tests_properties(run-small1-k-clique-listing-cpu-4 PROPERTIES  _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;6;add_test_mine;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;0;")
add_test(run-small1-k-clique-listing-cpu-2 "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/k-clique-listing-cpu" "-symmetricGraph" "-simpleGraph" "/work/08474/ywwu/ls6/Galois/inputs/Mining/citeseer.csgr" "-t" "2")
set_tests_properties(run-small1-k-clique-listing-cpu-2 PROPERTIES  _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;6;add_test_mine;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;0;")
add_test(run-small1-k-clique-listing-cpu-1 "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/k-clique-listing-cpu" "-symmetricGraph" "-simpleGraph" "/work/08474/ywwu/ls6/Galois/inputs/Mining/citeseer.csgr" "-t" "1")
set_tests_properties(run-small1-k-clique-listing-cpu-1 PROPERTIES  _BACKTRACE_TRIPLES "/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;6;add_test_mine;/work/08474/ywwu/ls6/Galois/lonestar/mining/cpu/k-clique-listing/CMakeLists.txt;0;")
